package ticmain;

import java.awt.Color;
import javax.swing.JOptionPane;
import static ticmain.Main.table;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainbt0 = new javax.swing.JButton();
        mainbt1 = new javax.swing.JButton();
        mainbt2 = new javax.swing.JButton();
        mainbt3 = new javax.swing.JButton();
        mainbt4 = new javax.swing.JButton();
        mainbt5 = new javax.swing.JButton();
        mainbt6 = new javax.swing.JButton();
        mainbt7 = new javax.swing.JButton();
        mainbt8 = new javax.swing.JButton();
        startbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        title_lable1 = new javax.swing.JLabel();
        title_lable2 = new javax.swing.JLabel();
        title_lable3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TicTacToe");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainbt0.setFont(mainbt0.getFont().deriveFont(mainbt0.getFont().getStyle() | java.awt.Font.BOLD, mainbt0.getFont().getSize()+8));
        mainbt0.setText("○");
        mainbt0.setEnabled(false);
        mainbt0.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt0.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt0ActionPerformed(evt);
            }
        });

        mainbt1.setFont(mainbt1.getFont().deriveFont(mainbt1.getFont().getStyle() | java.awt.Font.BOLD, mainbt1.getFont().getSize()+8));
        mainbt1.setText("○");
        mainbt1.setEnabled(false);
        mainbt1.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt1.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt1ActionPerformed(evt);
            }
        });

        mainbt2.setFont(mainbt2.getFont().deriveFont(mainbt2.getFont().getStyle() | java.awt.Font.BOLD, mainbt2.getFont().getSize()+8));
        mainbt2.setText("○");
        mainbt2.setEnabled(false);
        mainbt2.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt2.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt2ActionPerformed(evt);
            }
        });

        mainbt3.setFont(mainbt3.getFont().deriveFont(mainbt3.getFont().getStyle() | java.awt.Font.BOLD, mainbt3.getFont().getSize()+8));
        mainbt3.setText("○");
        mainbt3.setEnabled(false);
        mainbt3.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt3.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt3ActionPerformed(evt);
            }
        });

        mainbt4.setFont(mainbt4.getFont().deriveFont(mainbt4.getFont().getStyle() | java.awt.Font.BOLD, mainbt4.getFont().getSize()+8));
        mainbt4.setText("○");
        mainbt4.setEnabled(false);
        mainbt4.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt4.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt4ActionPerformed(evt);
            }
        });

        mainbt5.setFont(mainbt5.getFont().deriveFont(mainbt5.getFont().getStyle() | java.awt.Font.BOLD, mainbt5.getFont().getSize()+8));
        mainbt5.setText("○");
        mainbt5.setEnabled(false);
        mainbt5.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt5.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt5ActionPerformed(evt);
            }
        });

        mainbt6.setFont(mainbt6.getFont().deriveFont(mainbt6.getFont().getStyle() | java.awt.Font.BOLD, mainbt6.getFont().getSize()+8));
        mainbt6.setText("○");
        mainbt6.setEnabled(false);
        mainbt6.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt6.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt6ActionPerformed(evt);
            }
        });

        mainbt7.setFont(mainbt7.getFont().deriveFont(mainbt7.getFont().getStyle() | java.awt.Font.BOLD, mainbt7.getFont().getSize()+8));
        mainbt7.setText("○");
        mainbt7.setEnabled(false);
        mainbt7.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt7.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt7ActionPerformed(evt);
            }
        });

        mainbt8.setFont(mainbt8.getFont().deriveFont(mainbt8.getFont().getStyle() | java.awt.Font.BOLD, mainbt8.getFont().getSize()+8));
        mainbt8.setText("○");
        mainbt8.setEnabled(false);
        mainbt8.setMaximumSize(new java.awt.Dimension(75, 75));
        mainbt8.setMinimumSize(new java.awt.Dimension(75, 75));
        mainbt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbt8ActionPerformed(evt);
            }
        });

        startbtn.setFont(startbtn.getFont().deriveFont(startbtn.getFont().getSize()+6f));
        startbtn.setText("Start");
        startbtn.setActionCommand("開始");
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(exitbtn.getFont().deriveFont(exitbtn.getFont().getSize()+6f));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        title_lable1.setFont(title_lable1.getFont().deriveFont(title_lable1.getFont().getStyle() | java.awt.Font.BOLD, title_lable1.getFont().getSize()+2));
        title_lable1.setText("TicTacToe");
        title_lable1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        title_lable2.setFont(title_lable2.getFont().deriveFont(title_lable2.getFont().getStyle() | java.awt.Font.BOLD, title_lable2.getFont().getSize()+2));
        title_lable2.setText("By Bob Pan");
        title_lable2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        title_lable3.setFont(title_lable3.getFont().deriveFont(title_lable3.getFont().getStyle() | java.awt.Font.BOLD, title_lable3.getFont().getSize()+2));
        title_lable3.setText("2019.07.29");
        title_lable3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainbt3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainbt4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainbt5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainbt0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainbt1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainbt2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_lable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title_lable2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(title_lable3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainbt6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainbt7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainbt8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mainbt0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainbt1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainbt2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title_lable1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title_lable2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title_lable3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mainbt3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainbt4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainbt5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mainbt6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainbt7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainbt8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Tic Tac Toe");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.out.println("Exit pressed. Show confirm window.");
        exitconfirm();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Exit pressed. Show confirm window.");
        exitconfirm();
    }//GEN-LAST:event_formWindowClosing

    //將所有視窗物件設成初始值，遊戲重來
    private void gamestart() {
        System.out.println("Game Starting... Enable all buttoms...");
        mainbt0.setText("");
        mainbt1.setText("");
        mainbt2.setText("");
        mainbt3.setText("");
        mainbt4.setText("");
        mainbt5.setText("");
        mainbt6.setText("");
        mainbt7.setText("");
        mainbt8.setText("");
        mainbt0.setEnabled(true);
        mainbt1.setEnabled(true);
        mainbt2.setEnabled(true);
        mainbt3.setEnabled(true);
        mainbt4.setEnabled(true);
        mainbt5.setEnabled(true);
        mainbt6.setEnabled(true);
        mainbt7.setEnabled(true);
        mainbt8.setEnabled(true);
        mainbt0.setBackground(Color.lightGray);
        mainbt1.setBackground(Color.lightGray);
        mainbt2.setBackground(Color.lightGray);
        mainbt3.setBackground(Color.lightGray);
        mainbt4.setBackground(Color.lightGray);
        mainbt5.setBackground(Color.lightGray);
        mainbt6.setBackground(Color.lightGray);
        mainbt7.setBackground(Color.lightGray);
        mainbt8.setBackground(Color.lightGray);
    }

    private void comparebtn() {
        int player = 0;
        //有某行全部等於圈或等於叉，找出贏的那排並塗色
        if ((table[0] == 1 && table[1] == 1 && table[2] == 1)
                || (table[3] == 1 && table[4] == 1 && table[5] == 1)
                || (table[6] == 1 && table[7] == 1 && table[8] == 1)
                || (table[0] == 1 && table[3] == 1 && table[6] == 1)
                || (table[1] == 1 && table[4] == 1 && table[7] == 1)
                || (table[2] == 1 && table[5] == 1 && table[8] == 1)
                || (table[2] == 1 && table[4] == 1 && table[6] == 1)
                || (table[0] == 1 && table[4] == 1 && table[8] == 1)
                || (table[0] == 2 && table[1] == 2 && table[2] == 2)
                || (table[3] == 2 && table[4] == 2 && table[5] == 2)
                || (table[6] == 2 && table[7] == 2 && table[8] == 2)
                || (table[0] == 2 && table[3] == 2 && table[6] == 2)
                || (table[1] == 2 && table[4] == 2 && table[7] == 2)
                || (table[2] == 2 && table[5] == 2 && table[8] == 2)
                || (table[2] == 2 && table[4] == 2 && table[6] == 2)
                || (table[0] == 2 && table[4] == 2 && table[8] == 2)) {
            for (int l = 1; l <= 2; l++) {
                if (table[0] == l && table[1] == l && table[2] == l) {
                    player = l;
                    mainbt0.setBackground(Color.green);
                    mainbt1.setBackground(Color.green);
                    mainbt2.setBackground(Color.green);
                }
                if (table[3] == l && table[4] == l && table[5] == l) {
                    player = l;
                    mainbt3.setBackground(Color.green);
                    mainbt4.setBackground(Color.green);
                    mainbt5.setBackground(Color.green);
                }
                if (table[6] == l && table[7] == l && table[8] == l) {
                    player = l;
                    mainbt6.setBackground(Color.green);
                    mainbt7.setBackground(Color.green);
                    mainbt8.setBackground(Color.green);
                }
                if (table[0] == l && table[3] == l && table[6] == l) {
                    player = l;
                    mainbt0.setBackground(Color.green);
                    mainbt3.setBackground(Color.green);
                    mainbt6.setBackground(Color.green);
                }
                if (table[1] == l && table[4] == l && table[7] == l) {
                    player = l;
                    mainbt1.setBackground(Color.green);
                    mainbt4.setBackground(Color.green);
                    mainbt7.setBackground(Color.green);
                }
                if (table[2] == l && table[5] == l && table[8] == l) {
                    player = l;
                    mainbt2.setBackground(Color.green);
                    mainbt5.setBackground(Color.green);
                    mainbt8.setBackground(Color.green);
                }
                if (table[2] == l && table[4] == l && table[6] == l) {
                    player = l;
                    mainbt2.setBackground(Color.green);
                    mainbt4.setBackground(Color.green);
                    mainbt6.setBackground(Color.green);
                }
                if (table[0] == l && table[4] == l && table[8] == l) {
                    player = l;
                    mainbt0.setBackground(Color.green);
                    mainbt4.setBackground(Color.green);
                    mainbt8.setBackground(Color.green);
                }
            }
            playerwin(player);
            //如果沒有檢查是不是方格都填滿
        } else if (!(table[0] == 0
                || table[1] == 0
                || table[2] == 0
                || table[3] == 0
                || table[4] == 0
                || table[5] == 0
                || table[6] == 0
                || table[7] == 0
                || table[8] == 0)) {
            playerwin(3);
        }
    }

    //警告空格已有文字
    private void filled() {
        JOptionPane.showMessageDialog(null, "Already filled.", "Warning", JOptionPane.WARNING_MESSAGE);
    }

    //檢查傳入數據是圈獲勝、叉獲勝還是平手並彈出對話框
    private void playerwin(int player) {
        if (player == 1 || player == 2) {
            String name = "";
            switch (player) {
                case 1:
                    name = "○";
                    break;
                case 2:
                    name = "×";
                    break;
            }
            if (JOptionPane.showConfirmDialog(null, "Player \" " + name + " \"\nWin!\nReplay?", "Result", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                Main.resetact();
                gamestart();
            } else {
                System.exit(0);
            }

        } else {
            if (JOptionPane.showConfirmDialog(null, "Draw.\nReplay?", "Result", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                Main.resetact();
                gamestart();
            } else {
                System.exit(0);
            }
        }
    }
//開始按鈕按下後變Restart，為Restart時會有彈窗
    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        switch (startbtn.getText()) {
            case "Start":
                startbtn.setText("Restart");
                gamestart();
                break;
            case "Restart":
                if (JOptionPane.showConfirmDialog(null, "Are You Sure to Restart Game?", "Are You Sure?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                    Main.resetact();
                    gamestart();
                }
        }
    }//GEN-LAST:event_startbtnActionPerformed

    //流程說明：
    //將按鈕上顯示的文字轉換成數字(Main中的方法)
    //之後用(Main)中的方法判斷要填入圈還是叉後修改按鈕文字

    private void mainbt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt0ActionPerformed
        int btnstat = Main.detbtnstat(mainbt0.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(0, btnstat)) {
                case 1:
                    mainbt0.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt0.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt0ActionPerformed

    private void mainbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt1ActionPerformed
        int btnstat = Main.detbtnstat(mainbt1.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(1, btnstat)) {
                case 1:
                    mainbt1.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt1.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt1ActionPerformed

    private void mainbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt2ActionPerformed
        int btnstat = Main.detbtnstat(mainbt2.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(2, btnstat)) {
                case 1:
                    mainbt2.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt2.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt2ActionPerformed

    private void mainbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt3ActionPerformed
        int btnstat = Main.detbtnstat(mainbt3.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(3, btnstat)) {
                case 1:
                    mainbt3.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt3.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt3ActionPerformed

    private void mainbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt4ActionPerformed
        int btnstat = Main.detbtnstat(mainbt4.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(4, btnstat)) {
                case 1:
                    mainbt4.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt4.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt4ActionPerformed

    private void mainbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt5ActionPerformed
        int btnstat = Main.detbtnstat(mainbt5.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(5, btnstat)) {
                case 1:
                    mainbt5.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt5.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt5ActionPerformed

    private void mainbt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt6ActionPerformed
        int btnstat = Main.detbtnstat(mainbt6.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(6, btnstat)) {
                case 1:
                    mainbt6.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt6.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt6ActionPerformed

    private void mainbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt7ActionPerformed
        int btnstat = Main.detbtnstat(mainbt7.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(7, btnstat)) {
                case 1:
                    mainbt7.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt7.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt7ActionPerformed

    private void mainbt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbt8ActionPerformed
        int btnstat = Main.detbtnstat(mainbt8.getText());
        if (btnstat != 3) {
            switch (Main.btnpressedinit(8, btnstat)) {
                case 1:
                    mainbt8.setText("○");
                    comparebtn();
                    break;
                case 2:
                    mainbt8.setText("×");
                    comparebtn();
                    break;
                default:
                    filled();
                    break;
            }
        }
    }//GEN-LAST:event_mainbt8ActionPerformed

    private void exitconfirm() {
        //顯示離開提示並請使用者確認
        if (JOptionPane.showConfirmDialog(null, "Are You Sure to EXIT?", "Are You Sure?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton mainbt0;
    private javax.swing.JButton mainbt1;
    private javax.swing.JButton mainbt2;
    private javax.swing.JButton mainbt3;
    private javax.swing.JButton mainbt4;
    private javax.swing.JButton mainbt5;
    private javax.swing.JButton mainbt6;
    private javax.swing.JButton mainbt7;
    private javax.swing.JButton mainbt8;
    private javax.swing.JButton startbtn;
    private javax.swing.JLabel title_lable1;
    private javax.swing.JLabel title_lable2;
    private javax.swing.JLabel title_lable3;
    // End of variables declaration//GEN-END:variables
}
